dist: trusty
sudo: false
language: node_js
node_js:
- '6'
services:
- mongodb
cache: yarn
notifications:
  slack:
    rooms:
      secure: keWPbmcY6EfAIpyNzC/fBaJKCR3VDv7QZ43ED2XrlkXi2vy7Qe6g4Xbujl1mYC4dOPXrufRNl0NfyYyVEsDwtDI669aqIXvBQcwnIM+nOm6FDs4BXpxatOiPg49HtbkiEa/aog+FVmT45dHdDsbrDaoKHNyte3evnqStnohxU6fn6dZj+wMUbhLOhXQPAFmlFWwQEbZKRCHHa4o/F9coqmRlPsNyBhJkCv5u6l193ExDByLS/l79UYNuKo6fPH6zZD8db8+HoiO5c5FUT7WvzCbw5tBLk+2MvoAQg2Fyd56CxLKrvZM7bn46/yB+ObCtLeT6Xmy5pVnMeGrZSkpwW/Pw9HNMOpxOPnZW6424SJkI5mzrnFM1dS3YxPI6YPdnd4Jjszh1P0lru4iFOlUELeehLCGQzsg5mnl3s5LBTu6vAj8IR0VtgopGd6RH+KhqJ1af0mjtiHNwmscmcq8mMF71JVXqMy1rBO3E3rlJlxunY416NM08ybuHmUsiGcwIam0ohwfoC3FEAkSIA6i/pGcqXRYWd6eJ1kGf4T2wgxdFiN8gadIMRexa2nTcAkamxrr607RgSeV0uaCggRfhLzeDvZ9W6d0miuurNOMHHxcR8DevKd4ihpUV11cuxc6ZtiEX7oRj2K58rEEciDFHqmbBc6u5UBaK4wwPTrzV690=
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{branch}
      by %{author} %{result} in %{duration}
    on_pull_requests: false
deploy:
  provider: heroku
  api_key:
    secure: F8pXOLpjAaaSY4fA5UCCvBHCAItixlWX4Xo7J2i1Gcshv6AuZcTpS/YM3gBai4fG/VlSY7Dk1NceTVz34Ye51bXMOuncqkz30MxftDfwXzNDan4cc7wiwMYZlKA4poH2mdHfv8afGlN3RsWXzfm6UMHP+pPscm4QFDiwlPhkSFkemqPhusN43tC+daUn5H8rnnwyq+UyLHp4JgxElGg7CroOYxGEa3ZxRIbUi2rr8OE9oijF791n2bDlk+sX7T8CqSjrTEzGMTrEbYzc1WDk7obknrXLtB0Rt8+IS8DumWRd7j0nrVMekxOUeG5FLL/4yrq0b9+aSaNL4hh9nUDBT3GC+NCdBTPjL35JdC8+abexRhJX6rQcDmr4cukkw2j7yvsDBjxhVUV7kvMvFtOuLvsXTL2DFz3oeo1wD3djspNrMbQjklIQeEqSpk9arSbDbZIY1HDezRBQyiPRnC8de9gr8OWEFyfG3icgjzq32p70rR1eVECIT9o76YuVakD3gdug+BN77MLe+9TdFPUD0ePECoN8bd6Y0GNigfQUDbFQrdwWtqgCRLnhiQ9vsELwU/BtX1Gg2B6W9W8NYh/VAWkjCQkFT7gKCiUvsRTaZ0gvo7yDQ2ztax7v0epH6Sn+DpTw0oTvK0FXwkwbM5skwEza3x8fbBFkGsotXNygL4o=
  app: readably
  on:
    repo: melvinthemok/readably
