dist: trusty
sudo: false
language: node_js
node_js:
- '6'
services:
- mongodb
cache: yarn
notifications:
  slack:
    secure: hgKpT9OF+VGmvlaTp8xJyJ2o/h31A+SXIfJK0cWV2M/gWLE6DAchTY3XuEf8Wxl4OGm6cZigiRgabMao40IabzKmzAwehoL16PpHqNmtghrk2rwIL41i3QFClTS3CwwwxO5KjAnYs8W5KSnjM7y6gDqorpjHD5eSKCNsE6Rt8o1Rd2TGmgMGfs5X2hamMYPesIIZYYYbZrNeUFYUjRrt0OxUyB8jVcjVH4Oo4lNtrDPosamPct6W6oL/gBXwGM4O9rK44nVGzmXOvF0uhaLsITI0Ql2PaokrUaXf8Lr78xrF98qUh+hc/TNl8gpRu4ZsVw1eOi8EPiISy24EAkg5KLDsFmcY9ujgpol07+u0ZpKvQ7bD82iSzpyD6+K0JztT9Q2lA5EOJtSmdsAJKpQz3xpGkIN/O8rvSoR/KVGvLA/c3mwFcL2nHdeZlEGu+3eHtVoG4kyn+kXP19LW73IMz3/UeyD0lVhl5emSqazuLJl/T3qiIH24CstboAwCd2e3I89qjECihOVjDcQklWuS5fcybElpbxKAZYG1NCmtba52pHkkZRLpcqaXgmSxrNA1Yu93jOfLxRSzpg9wbXmYILvtZUu/Tq+G8VEPA/yH7rUkVz9sIjiNzJ1RuJyUlrSxYA70quZ15BBzXvvimEEFHXI1vUqPaZlgg1mssm/xZLY=
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{branch}
      by %{author} %{result} in %{duration}
    on_pull_requests: false
deploy:
  provider: heroku
  api_key:
    secure: F8pXOLpjAaaSY4fA5UCCvBHCAItixlWX4Xo7J2i1Gcshv6AuZcTpS/YM3gBai4fG/VlSY7Dk1NceTVz34Ye51bXMOuncqkz30MxftDfwXzNDan4cc7wiwMYZlKA4poH2mdHfv8afGlN3RsWXzfm6UMHP+pPscm4QFDiwlPhkSFkemqPhusN43tC+daUn5H8rnnwyq+UyLHp4JgxElGg7CroOYxGEa3ZxRIbUi2rr8OE9oijF791n2bDlk+sX7T8CqSjrTEzGMTrEbYzc1WDk7obknrXLtB0Rt8+IS8DumWRd7j0nrVMekxOUeG5FLL/4yrq0b9+aSaNL4hh9nUDBT3GC+NCdBTPjL35JdC8+abexRhJX6rQcDmr4cukkw2j7yvsDBjxhVUV7kvMvFtOuLvsXTL2DFz3oeo1wD3djspNrMbQjklIQeEqSpk9arSbDbZIY1HDezRBQyiPRnC8de9gr8OWEFyfG3icgjzq32p70rR1eVECIT9o76YuVakD3gdug+BN77MLe+9TdFPUD0ePECoN8bd6Y0GNigfQUDbFQrdwWtqgCRLnhiQ9vsELwU/BtX1Gg2B6W9W8NYh/VAWkjCQkFT7gKCiUvsRTaZ0gvo7yDQ2ztax7v0epH6Sn+DpTw0oTvK0FXwkwbM5skwEza3x8fbBFkGsotXNygL4o=
  app: readably
  on:
    repo: melvinthemok/readably
