var express = require('express')
var router = express.Router()
var isAdminOrCatchPlus = require('../middleware/isAdminOrCatchPlus')
var isTutor = require('../middleware/isTutor')
var studentController = require('../controllers/studentController')

router.get('/', studentController.index)
router.get('/new', studentController.new)
router.get('/attendance', studentController.attendance.edit)
router.put('/attendance', isAdminOrCatchPlus, studentController.attendance.update)

router.get('/pre-school', studentController.preSchool.index)
router.get('/pre-school/archived', studentController.preSchool.indexArchived)
router.get('/pre-school/new', isAdminOrCatchPlus, studentController.preSchool.new)
router.get('/pre-school/:id', studentController.preSchool.show)
router.get('/pre-school/edit/:id', studentController.preSchool.edit)
router.get('/pre-school/attend/:id', isTutor, studentController.preSchool.newAttend)
router.post('/pre-school', isAdminOrCatchPlus, studentController.preSchool.create)
router.put('/pre-school/update/:id', isTutor, studentController.preSchool.update)
router.put('/pre-school/attend/:id', isTutor, studentController.preSchool.createAttend)

router.get('/fitzroy', studentController.fitzroy.index)
router.get('/fitzroy/archived', studentController.fitzroy.indexArchived)
router.get('/fitzroy/new', isAdminOrCatchPlus, studentController.fitzroy.new)
router.get('/fitzroy/:id', studentController.fitzroy.show)
router.get('/fitzroy/edit/:id', studentController.fitzroy.edit)
router.get('/fitzroy/attend/:id', isTutor, studentController.fitzroy.newAttend)
router.post('/fitzroy', isAdminOrCatchPlus, studentController.fitzroy.create)
router.put('/fitzroy/update/:id', isTutor, studentController.fitzroy.update)
router.put('/fitzroy/attend/:id', isTutor, studentController.fitzroy.createAttend)

router.get('/post-fitzroy', studentController.postFitzroy.index)
router.get('/post-fitzroy/archived', studentController.postFitzroy.indexArchived)
router.get('/post-fitzroy/new', isAdminOrCatchPlus, studentController.postFitzroy.new)
router.get('/post-fitzroy/:id', studentController.postFitzroy.show)
router.get('/post-fitzroy/edit/:id', studentController.postFitzroy.edit)
router.get('/post-fitzroy/attend/:id', isTutor, studentController.postFitzroy.newAttend)
router.post('/post-fitzroy', isAdminOrCatchPlus, studentController.postFitzroy.create)
router.put('/post-fitzroy/update/:id', isTutor, studentController.postFitzroy.update)
router.put('/post-fitzroy/attend/:id', isTutor, studentController.postFitzroy.createAttend)

module.exports = router